name: Coveo
on:
  push:
    branches: [ "main" ]
jobs:
  coveo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Authenticate to Coveo
        run: npx @coveo/cli auth:token -t=${{ secrets.COVEO_API_KEY }}
      - name: List organizations
        run: npx @coveo/cli org:list
